//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.Dictionaries", typeof(Dictionaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8140	丂	gnv	gnv	kao3;yu2
        ///8141	丄	hgd	hgd	shang4
        ///8142	丅	ghk	ghk	xia4
        ///8143	丆	dgt	dgt	shi2
        ///8144	丏	ghnn	ghnn	mian3
        ///8145	丒	vygf	vygf	chou3
        ///8146	丗	gkgd	gkgd	shi4
        ///8147	丟	gcu	gcu	diu1
        ///8148	丠	uxgf	uxgf	qiu1
        ///8149	両	gmmk	gmmk	liang3
        ///814A	丣	gajn	gjan	you3
        ///814B	並	uogf	uof	bing4;bang4
        ///814C	丩	nhk	nhk	jiu1
        ///814D	丮	nfhk	ngk	ji3
        ///814E	丯	ehk	ehk	jie4
        ///814F	丱	njhg	jnhg	guan4;kuang4
        ///8150	丳	kkjk	kkjk	chan3
        ///8151	丵	oguf	oufj	zhuo2
        ///8152	丷	uyt	uyt	ba1
        ///8153	丼	fjyi	fjyi	jing3;dan3
        ///8154	乀	yyll	yyll	fu2
        ///8155	乁	yyll	gyi	f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChineseCode {
            get {
                return ResourceManager.GetString("ChineseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,a
        ///2,ai
        ///3,an
        ///4,ang
        ///5,ao
        ///7,ba
        ///8,bai
        ///9,ban
        ///10,bang
        ///11,bao
        ///12,bei
        ///13,ben
        ///14,beng
        ///15,bi
        ///16,bian
        ///18,biao
        ///19,bie
        ///20,bin
        ///21,bing
        ///22,bo
        ///23,bu
        ///25,ca
        ///26,cai
        ///27,can
        ///28,cang
        ///29,cao
        ///30,ce
        ///31,cen
        ///32,ceng
        ///33,cha
        ///34,chai
        ///35,chan
        ///36,chang
        ///37,chao
        ///38,che
        ///39,chen
        ///40,cheng
        ///41,chi
        ///42,chong
        ///43,chou
        ///44,chu
        ///45,chuai
        ///46,chuan
        ///47,chuang
        ///48,chui
        ///49,chun
        ///50,chuo
        ///51,ci
        ///52,cong
        ///53,cou
        ///54,cu
        ///56,cuan
        ///59,cui
        ///60,cun
        ///61,cuo
        ///63,da
        ///64,dai
        ///65,dan
        ///66,dang
        ///67,dao
        ///68,de
        ///69,dei
        ///70,den
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TouchPalPinyinDic {
            get {
                return ResourceManager.GetString("TouchPalPinyinDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;liao&apos;jie 了解
        ///&apos;mu&apos;di 目的
        ///&apos;ji&apos;ou 奇偶
        ///&apos;zhong&apos;yao 重要
        ///&apos;hang&apos;ye 行业
        ///&apos;zhong&apos;dian 重点
        ///&apos;yin&apos;yue 音乐
        ///&apos;zhong&apos;da 重大
        ///&apos;yin&apos;hang 银行
        ///&apos;pai&apos;hang 排行
        ///&apos;yan&apos;zhong 严重
        ///&apos;zeng&apos;zhang 增长
        ///&apos;zhong&apos;shi 重视
        ///&apos;xie&apos;tiao 协调
        ///&apos;zeng&apos;yi 曾毅
        ///&apos;du&apos;shi 都市
        ///&apos;zun&apos;zhong 尊重
        ///&apos;cheng&apos;zhang 成长
        ///&apos;da&apos;sha 大厦
        ///&apos;zhu&apos;zhong 注重
        ///&apos;bu&apos;liao 不了
        ///&apos;du&apos;hui 都会
        ///&apos;zhan&apos;zhang 站长
        ///&apos;xi&apos;zang 西藏
        ///&apos;kuai&apos;ji 会计
        ///&apos;tiao&apos;kong 调控
        ///&apos;zi&apos;xi 仔细
        ///&apos;bu&apos;zhang 部长
        ///&apos;ju&apos;zhang 局长
        ///&apos;yuan&apos;zhang 院长
        ///&apos;shou&apos;du 首都
        ///&apos;sheng&apos;zhang 生长
        ///&apos;zhong&apos;liang 重量
        ///&apos;kong&apos;tiao 空调
        ///&apos;xiao&apos;zhang 校长
        ///&apos;long&apos;zhong 隆重
        ///&apos;j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordPinyin {
            get {
                return ResourceManager.GetString("WordPinyin", resourceCulture);
            }
        }
    }
}
