//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PinyinDic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinDic() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.PinyinDic", typeof(PinyinDic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 啊,a
        ///啊,e
        ///阿,a
        ///阿,e
        ///呵,a
        ///呵,ha
        ///呵,he
        ///呵,ke
        ///吖,a
        ///吖,ya
        ///嗄,a
        ///嗄,sha
        ///嗄,xia
        ///腌,a
        ///腌,yan
        ///锕,a
        ///锕,ke
        ///錒,a
        ///錒,ke
        ///厑,aes
        ///爱,ai
        ///矮,ai
        ///挨,ai
        ///哎,ai
        ///碍,ai
        ///癌,ai
        ///艾,ai
        ///艾,yi
        ///唉,ai
        ///哀,ai
        ///蔼,ai
        ///隘,ai
        ///隘,e
        ///埃,ai
        ///埃,zhi
        ///皑,ai
        ///呆,ai
        ///呆,bao
        ///呆,dai
        ///嗌,ai
        ///嗌,wo
        ///嗌,yi
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///捱,ai
        ///砹,ai
        ///嗳,ai
        ///锿,ai
        ///霭,ai
        ///乂,ai
        ///乂,yi
        ///乃,ai
        ///乃,nai
        ///伌,ai
        ///僾,ai
        ///儗,ai
        ///儗,ni
        ///儗,yi
        ///凒,ai
        ///剀,ai
        ///剀,kai
        ///剴,ai
        ///剴,kai
        ///叆,ai
        ///叆,yi
        ///呃,ai
        ///呃,e
        ///呝,ai
        ///呝,e
        ///啀,ai
        ///嘊,ai
        ///噫,ai
        ///噫,yi
        ///噯,ai
        ///堨,ai
        ///堨,e
        ///堨,ye
        ///塧,ai
        ///壒,ai
        ///奇,ai
        ///奇,ji
        ///奇,qi
        ///奇,yi
        ///娭,ai
        ///娭,xi
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AllPinYin {
            get {
                return ResourceManager.GetString("AllPinYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A;阿吖嗄腌锕 Ai;埃挨哎唉哀皑癌蔼矮艾碍爱隘捱嗳嗌嫒瑷暧砹锿霭 An;鞍氨安俺按暗岸胺案谙埯揞庵桉铵鹌黯 Ang;肮昂盎 Ao;凹敖熬翱袄傲奥懊澳坳嗷岙廒遨媪骜獒聱螯鏊鳌鏖 Ba;芭捌扒叭吧笆八疤巴拔跋靶把耙坝霸罢爸茇菝岜灞钯粑鲅魃 Bai;白柏百摆佰败拜稗捭掰 Ban;斑班搬扳般颁板版扮拌伴瓣半办绊阪坂钣瘢癍舨 Bang;邦帮梆榜膀绑棒磅镑傍谤蒡浜 Beng;蚌崩绷甭泵蹦迸嘣甏 Bao;苞胞包褒薄雹保堡饱宝抱报暴豹鲍爆曝勹葆孢煲鸨褓趵龅 Bo;剥玻菠播拨钵波博勃搏铂箔伯帛舶脖膊渤泊驳亳啵饽檗擘礴钹鹁簸跛踣 Bei;杯碑悲卑北辈背贝钡倍狈备惫焙被孛陂邶蓓呗悖碚鹎褙鐾鞴 Ben;奔苯本笨畚坌锛 Bi;逼鼻比鄙笔彼碧蓖蔽毕毙毖币庇痹闭敝弊必壁臂避陛匕俾荜荸萆薜吡哔狴庳愎滗濞弼妣婢嬖璧贲睥畀铋秕裨筚箅篦舭襞跸髀 Pi;辟坯砒霹批披劈琵毗啤脾疲皮匹痞僻屁譬丕仳陴邳郫圮埤鼙芘擗噼庀淠媲纰枇甓罴铍癖疋蚍蜱貔 Bian;鞭边编贬扁便变卞辨辩辫遍匾弁苄忭汴缏煸砭碥窆褊蝙笾鳊 Biao;标彪膘表婊骠飑飙飚镖镳瘭裱鳔 Bie;鳖憋别瘪蹩 Bin;彬斌濒滨宾摈傧豳缤玢槟殡膑镔髌鬓 Bing;兵冰柄丙秉饼炳病并禀邴摒 Bu;捕卜 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SinglePinYin {
            get {
                return ResourceManager.GetString("SinglePinYin", resourceCulture);
            }
        }
    }
}
