//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PinyinDic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinDic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.PinyinDic", typeof(PinyinDic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〇,ling
        ///啊,a
        ///啊,e
        ///阿,a
        ///阿,e
        ///呵,a
        ///呵,ha
        ///呵,he
        ///呵,ke
        ///吖,a
        ///吖,ya
        ///嗄,a
        ///嗄,sha
        ///嗄,xia
        ///腌,a
        ///腌,yan
        ///锕,a
        ///锕,ke
        ///錒,a
        ///錒,ke
        ///厑,aes
        ///爱,ai
        ///矮,ai
        ///挨,ai
        ///哎,ai
        ///碍,ai
        ///癌,ai
        ///艾,ai
        ///艾,yi
        ///唉,ai
        ///哀,ai
        ///蔼,ai
        ///隘,ai
        ///隘,e
        ///埃,ai
        ///埃,zhi
        ///皑,ai
        ///呆,ai
        ///呆,bao
        ///呆,dai
        ///嗌,ai
        ///嗌,wo
        ///嗌,yi
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///捱,ai
        ///砹,ai
        ///嗳,ai
        ///锿,ai
        ///霭,ai
        ///乂,ai
        ///乂,yi
        ///乃,ai
        ///乃,nai
        ///伌,ai
        ///僾,ai
        ///儗,ai
        ///儗,ni
        ///儗,yi
        ///凒,ai
        ///剀,ai
        ///剀,kai
        ///剴,ai
        ///剴,kai
        ///叆,ai
        ///叆,yi
        ///呃,ai
        ///呃,e
        ///呝,ai
        ///呝,e
        ///啀,ai
        ///嘊,ai
        ///噫,ai
        ///噫,yi
        ///噯,ai
        ///堨,ai
        ///堨,e
        ///堨,ye
        ///塧,ai
        ///壒,ai
        ///奇,ai
        ///奇,ji
        ///奇,qi
        ///奇,yi
        ///娭,ai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllPinYin {
            get {
                return ResourceManager.GetString("AllPinYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〇,ling
        ///啊,a
        ///阿,a
        ///吖,a
        ///嗄,a
        ///腌,a
        ///锕,a
        ///埃,ai
        ///挨,ai
        ///哎,ai
        ///唉,ai
        ///哀,ai
        ///皑,ai
        ///癌,ai
        ///蔼,ai
        ///矮,ai
        ///艾,ai
        ///碍,ai
        ///爱,ai
        ///隘,ai
        ///捱,ai
        ///嗳,ai
        ///嗌,ai
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///砹,ai
        ///锿,ai
        ///霭,ai
        ///鞍,an
        ///氨,an
        ///安,an
        ///俺,an
        ///按,an
        ///暗,an
        ///岸,an
        ///胺,an
        ///案,an
        ///谙,an
        ///埯,an
        ///揞,an
        ///庵,an
        ///桉,an
        ///铵,an
        ///鹌,an
        ///黯,an
        ///肮,ang
        ///昂,ang
        ///盎,ang
        ///凹,ao
        ///敖,ao
        ///熬,ao
        ///翱,ao
        ///袄,ao
        ///傲,ao
        ///奥,ao
        ///懊,ao
        ///澳,ao
        ///坳,ao
        ///嗷,ao
        ///岙,ao
        ///廒,ao
        ///遨,ao
        ///媪,ao
        ///骜,ao
        ///獒,ao
        ///聱,ao
        ///螯,ao
        ///鏊,ao
        ///鳌,ao
        ///鏖,ao
        ///芭,ba
        ///捌,ba
        ///扒,ba
        ///叭,ba
        ///吧,ba
        ///笆,ba
        ///八,ba
        ///疤,ba
        ///巴,ba
        ///拔,ba
        ///跋,ba
        ///靶,ba
        ///把,ba
        ///耙,ba
        ///坝,b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SinglePinYin {
            get {
                return ResourceManager.GetString("SinglePinYin", resourceCulture);
            }
        }
    }
}
