//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PinyinDic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinDic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.PinyinDic", typeof(PinyinDic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〇,ling
        ///啊,a
        ///啊,e
        ///阿,a
        ///阿,e
        ///呵,a
        ///呵,ha
        ///呵,he
        ///呵,ke
        ///吖,a
        ///吖,ya
        ///嗄,a
        ///嗄,sha
        ///嗄,xia
        ///腌,a
        ///腌,yan
        ///锕,a
        ///锕,ke
        ///錒,a
        ///錒,ke
        ///厑,aes
        ///爱,ai
        ///矮,ai
        ///挨,ai
        ///哎,ai
        ///碍,ai
        ///癌,ai
        ///艾,ai
        ///艾,yi
        ///唉,ai
        ///哀,ai
        ///蔼,ai
        ///隘,ai
        ///隘,e
        ///埃,ai
        ///埃,zhi
        ///皑,ai
        ///呆,ai
        ///呆,bao
        ///呆,dai
        ///嗌,ai
        ///嗌,wo
        ///嗌,yi
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///捱,ai
        ///砹,ai
        ///嗳,ai
        ///锿,ai
        ///霭,ai
        ///乂,ai
        ///乂,yi
        ///乃,ai
        ///乃,nai
        ///伌,ai
        ///僾,ai
        ///儗,ai
        ///儗,ni
        ///儗,yi
        ///凒,ai
        ///剀,ai
        ///剀,kai
        ///剴,ai
        ///剴,kai
        ///叆,ai
        ///叆,yi
        ///呃,ai
        ///呃,e
        ///呝,ai
        ///呝,e
        ///啀,ai
        ///嘊,ai
        ///噫,ai
        ///噫,yi
        ///噯,ai
        ///堨,ai
        ///堨,e
        ///堨,ye
        ///塧,ai
        ///壒,ai
        ///奇,ai
        ///奇,ji
        ///奇,qi
        ///奇,yi
        ///娭,ai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllPinYin {
            get {
                return ResourceManager.GetString("AllPinYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〇,ling
        ///爱,ai
        ///矮,ai
        ///挨,ai
        ///哎,ai
        ///碍,ai
        ///癌,ai
        ///唉,ai
        ///哀,ai
        ///蔼,ai
        ///皑,ai
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///捱,ai
        ///砹,ai
        ///嗳,ai
        ///锿,ai
        ///霭,ai
        ///伌,ai
        ///僾,ai
        ///凒,ai
        ///啀,ai
        ///嘊,ai
        ///噯,ai
        ///塧,ai
        ///壒,ai
        ///嬡,ai
        ///愛,ai
        ///懓,ai
        ///昹,ai
        ///曖,ai
        ///毐,ai
        ///溰,ai
        ///溾,ai
        ///璦,ai
        ///皚,ai
        ///皧,ai
        ///瞹,ai
        ///硋,ai
        ///薆,ai
        ///藹,ai
        ///譪,ai
        ///躷,ai
        ///鎄,ai
        ///鑀,ai
        ///靄,ai
        ///馤,ai
        ///鱫,ai
        ///鴱,ai
        ///按,an
        ///安,an
        ///暗,an
        ///岸,an
        ///案,an
        ///鞍,an
        ///氨,an
        ///铵,an
        ///桉,an
        ///黯,an
        ///侒,an
        ///儑,an
        ///唵,an
        ///啽,an
        ///垵,an
        ///堓,an
        ///峖,an
        ///盦,an
        ///盫,an
        ///罯,an
        ///腤,an
        ///荌,an
        ///萻,an
        ///蓭,an
        ///誝,an
        ///豻,an
        ///貋,an
        ///銨,an
        ///錌,an
        ///隌,an
        ///雸,an
        ///鞌,an
        ///韽,an
        ///馣,an
        ///鮟,an
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SinglePinYin {
            get {
                return ResourceManager.GetString("SinglePinYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;yun&apos;diao 韵调
        ///&apos;yun&apos;huo 匀和
        ///&apos;bian&apos;diao 变调
        ///&apos;bo&apos;hou 薄厚
        ///&apos;bo&apos;jiu 薄酒
        ///&apos;bian&apos;jiao 编校
        ///&apos;bian&apos;qia 边卡
        ///&apos;kui&apos;duo 揆度
        ///&apos;kui&apos;duo 窥度
        ///&apos;yun&apos;jie 蕴藉
        ///&apos;kui&apos;she 亏折
        ///&apos;yun&apos;chen 匀称
        ///&apos;yu&apos;diao 语调
        ///&apos;bo&apos;le 伯乐
        ///&apos;yu&apos;dou 于都
        ///&apos;bing&apos;zu 兵卒
        ///&apos;bo&apos;li 薄利
        ///&apos;bo&apos;li 薄礼
        ///&apos;yu&apos;chi 尉迟
        ///&apos;bo&apos;lin 柏林
        ///&apos;bo&apos;he 薄荷
        ///&apos;bo&apos;le 博乐
        ///&apos;lao&apos;ren 落忍
        ///&apos;hui&apos;nong 溃脓
        ///&apos;kuang&apos;zhang 矿长
        ///&apos;ji&apos;bo 瘠薄
        ///&apos;bi&apos;yang 泌阳
        ///&apos;yun&apos;xing 运行
        ///&apos;bi&apos;zhong 比重
        ///&apos;ji&apos;cha 级差
        ///&apos;kuan&apos;zhi 款识
        ///&apos;yuan&apos;xing 远行
        ///&apos;huo&apos;de 霍地
        ///&apos;bie&apos;zhuan 别传
        ///&apos;bie&apos;jie 别价
        ///&apos;la&apos;li 癞痢
        ///&apos;la&apos;qian 拉纤
        ///&apos;za&apos;jia 咱家
        ///&apos;bi&apos;xie 辟邪
        ///&apos;bi&apos;xie 鼻 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordPinyin {
            get {
                return ResourceManager.GetString("WordPinyin", resourceCulture);
            }
        }
    }
}
