//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyzy.IMEWLConverter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PinyinDic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PinyinDic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Studyzy.IMEWLConverter.PinyinDic", typeof(PinyinDic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〇,ling
        ///啊,a
        ///啊,e
        ///阿,a
        ///阿,e
        ///呵,a
        ///呵,ha
        ///呵,he
        ///呵,ke
        ///吖,a
        ///吖,ya
        ///嗄,a
        ///嗄,sha
        ///嗄,xia
        ///腌,a
        ///腌,yan
        ///锕,a
        ///锕,ke
        ///錒,a
        ///錒,ke
        ///爱,ai
        ///矮,ai
        ///挨,ai
        ///哎,ai
        ///碍,ai
        ///癌,ai
        ///艾,ai
        ///艾,yi
        ///唉,ai
        ///哀,ai
        ///蔼,ai
        ///隘,ai
        ///隘,e
        ///埃,ai
        ///埃,zhi
        ///皑,ai
        ///呆,ai
        ///呆,bao
        ///呆,dai
        ///嗌,ai
        ///嗌,wo
        ///嗌,yi
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///捱,ai
        ///砹,ai
        ///嗳,ai
        ///锿,ai
        ///霭,ai
        ///乂,ai
        ///乂,yi
        ///乃,ai
        ///乃,nai
        ///伌,ai
        ///僾,ai
        ///儗,ai
        ///儗,ni
        ///儗,yi
        ///凒,ai
        ///剀,ai
        ///剀,kai
        ///剴,ai
        ///剴,kai
        ///叆,ai
        ///叆,yi
        ///呃,ai
        ///呃,e
        ///呝,ai
        ///呝,e
        ///啀,ai
        ///嘊,ai
        ///噫,ai
        ///噫,yi
        ///噯,ai
        ///堨,ai
        ///堨,e
        ///堨,ye
        ///塧,ai
        ///壒,ai
        ///奇,ai
        ///奇,ji
        ///奇,qi
        ///奇,yi
        ///娭,ai
        ///娭,xi        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllPinYin {
            get {
                return ResourceManager.GetString("AllPinYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阿,a
        ///啊,a
        ///呵,he
        ///腌,yan
        ///嗬,he
        ///嗄,a
        ///锕,a
        ///吖,a
        ///錒,a
        ///醃,a
        ///爱,ai
        ///碍,ai
        ///艾,ai
        ///哀,ai
        ///挨,ai
        ///埃,ai
        ///矮,ai
        ///唉,ai
        ///哎,ai
        ///蔼,ai
        ///癌,ai
        ///隘,ai
        ///霭,ai
        ///暧,ai
        ///嗳,ai
        ///捱,ai
        ///皑,ai
        ///噫,yi
        ///瑷,ai
        ///嫒,ai
        ///嗌,ai
        ///毐,ai
        ///僾,ai
        ///诶,ei
        ///锿,ai
        ///砹,ai
        ///鴱,ai
        ///鱫,ai
        ///騃,ai
        ///馤,ai
        ///餲,ai
        ///靉,ai
        ///靄,ai
        ///隑,ai
        ///阨,ai
        ///鑀,ai
        ///鎄,ai
        ///躷,ai
        ///賹,ai
        ///譺,ai
        ///譪,ai
        ///諰,shai
        ///誒,ei
        ///藹,ai
        ///薆,ai
        ///絠,ai
        ///礙,ai
        ///磑,gai
        ///硙,wei
        ///硋,ai
        ///瞹,ai
        ///皧,ai
        ///皚,ai
        ///璦,ai
        ///焥,ai
        ///濭,ai
        ///溾,ai
        ///溰,ai
        ///欸,ai
        ///欬,ai
        ///曖,ai
        ///昹,ai
        ///敳,ai
        ///敱,ai
        ///懝,ai
        ///懓,ai
        ///愛,ai
        ///嵦,ai
        ///嬡,ai
        ///娾,ai
        ///娭,ai
        ///壒,ai
        ///塧,ai
        ///堨,ai
        ///噯,ai
        ///嘊,ai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SinglePinYin {
            get {
                return ResourceManager.GetString("SinglePinYin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,a
        ///2,ai
        ///3,an
        ///4,ang
        ///5,ao
        ///7,ba
        ///8,bai
        ///9,ban
        ///10,bang
        ///11,bao
        ///12,bei
        ///13,ben
        ///14,beng
        ///15,bi
        ///16,bian
        ///18,biao
        ///19,bie
        ///20,bin
        ///21,bing
        ///22,bo
        ///23,bu
        ///25,ca
        ///26,cai
        ///27,can
        ///28,cang
        ///29,cao
        ///30,ce
        ///31,cen
        ///32,ceng
        ///33,cha
        ///34,chai
        ///35,chan
        ///36,chang
        ///37,chao
        ///38,che
        ///39,chen
        ///40,cheng
        ///41,chi
        ///42,chong
        ///43,chou
        ///44,chu
        ///45,chuai
        ///46,chuan
        ///47,chuang
        ///48,chui
        ///49,chun
        ///50,chuo
        ///51,ci
        ///52,cong
        ///53,cou
        ///54,cu
        ///56,cuan
        ///59,cui
        ///60,cun
        ///61,cuo
        ///63,da
        ///64,dai
        ///65,dan
        ///66,dang
        ///67,dao
        ///68,de
        ///69,dei
        ///70,den
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TouchPalPinyinDic {
            get {
                return ResourceManager.GetString("TouchPalPinyinDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;liao&apos;jie 了解
        ///&apos;mu&apos;di 目的
        ///&apos;ji&apos;ou 奇偶
        ///&apos;zhong&apos;yao 重要
        ///&apos;hang&apos;ye 行业
        ///&apos;zhong&apos;dian 重点
        ///&apos;yin&apos;yue 音乐
        ///&apos;zhong&apos;da 重大
        ///&apos;yin&apos;hang 银行
        ///&apos;pai&apos;hang 排行
        ///&apos;yan&apos;zhong 严重
        ///&apos;zeng&apos;zhang 增长
        ///&apos;zhong&apos;shi 重视
        ///&apos;xie&apos;tiao 协调
        ///&apos;zeng&apos;yi 曾毅
        ///&apos;du&apos;shi 都市
        ///&apos;zun&apos;zhong 尊重
        ///&apos;cheng&apos;zhang 成长
        ///&apos;da&apos;sha 大厦
        ///&apos;zhu&apos;zhong 注重
        ///&apos;bu&apos;liao 不了
        ///&apos;du&apos;hui 都会
        ///&apos;zhan&apos;zhang 站长
        ///&apos;xi&apos;zang 西藏
        ///&apos;kuai&apos;ji 会计
        ///&apos;tiao&apos;kong 调控
        ///&apos;zi&apos;xi 仔细
        ///&apos;bu&apos;zhang 部长
        ///&apos;ju&apos;zhang 局长
        ///&apos;yuan&apos;zhang 院长
        ///&apos;shou&apos;du 首都
        ///&apos;sheng&apos;zhang 生长
        ///&apos;zhong&apos;liang 重量
        ///&apos;kong&apos;tiao 空调
        ///&apos;xiao&apos;zhang 校长
        ///&apos;long&apos;zhong 隆重
        ///&apos;j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordPinyin {
            get {
                return ResourceManager.GetString("WordPinyin", resourceCulture);
            }
        }
    }
}
